name: Sync Upstream

permissions: write-all              # grant write permission

on: 
  schedule:
    - cron: '0 0 * * *'            # scheduled for 00:00 every Monday
  workflow_dispatch:                # trigger manually

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main             # set the branch to merge to
          fetch-depth: 0 
      - name: Sync Upstream
        uses: zhangnew/sync-upstream@v1
        with:
          upstream: hkshitesh/LAB-SUBMISSION-CONTAINER-ORCHESTRATION-AND-SECURITY-JAN-JUNE-2026      # set the upstream repo
          upstream-branch: main   # set the upstream branch to merge from
          branch: main          # set the branch to merge to
  
